name: ci

on: [push, pull_request] # Run on Push and Pull Requests

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 13.x] # Only run the 10.x, 12.x, 13.x build

    steps:
      - uses: actions/checkout@v1
      - name: Checkout ğŸ›ï¸ ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install -g yarn
      - name: Install and Build ğŸ”§ & Test ğŸš€
        run: |
          yarn
          yarn build
